// Code generated by protoc-gen-go. DO NOT EDIT.
// source: library.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IssueBookReq struct {
	Api                  string   `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	Book                 *Book    `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	IssuerName           string   `protobuf:"bytes,3,opt,name=IssuerName,proto3" json:"IssuerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueBookReq) Reset()         { *m = IssueBookReq{} }
func (m *IssueBookReq) String() string { return proto.CompactTextString(m) }
func (*IssueBookReq) ProtoMessage()    {}
func (*IssueBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1c5bd42931444, []int{0}
}

func (m *IssueBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueBookReq.Unmarshal(m, b)
}
func (m *IssueBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueBookReq.Marshal(b, m, deterministic)
}
func (m *IssueBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueBookReq.Merge(m, src)
}
func (m *IssueBookReq) XXX_Size() int {
	return xxx_messageInfo_IssueBookReq.Size(m)
}
func (m *IssueBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_IssueBookReq proto.InternalMessageInfo

func (m *IssueBookReq) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *IssueBookReq) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *IssueBookReq) GetIssuerName() string {
	if m != nil {
		return m.IssuerName
	}
	return ""
}

type IssueBookResp struct {
	Api                  string   `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	Book                 *Book    `protobuf:"bytes,2,opt,name=Book,proto3" json:"Book,omitempty"`
	IssuerName           string   `protobuf:"bytes,3,opt,name=IssuerName,proto3" json:"IssuerName,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueBookResp) Reset()         { *m = IssueBookResp{} }
func (m *IssueBookResp) String() string { return proto.CompactTextString(m) }
func (*IssueBookResp) ProtoMessage()    {}
func (*IssueBookResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1c5bd42931444, []int{1}
}

func (m *IssueBookResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueBookResp.Unmarshal(m, b)
}
func (m *IssueBookResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueBookResp.Marshal(b, m, deterministic)
}
func (m *IssueBookResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueBookResp.Merge(m, src)
}
func (m *IssueBookResp) XXX_Size() int {
	return xxx_messageInfo_IssueBookResp.Size(m)
}
func (m *IssueBookResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueBookResp.DiscardUnknown(m)
}

var xxx_messageInfo_IssueBookResp proto.InternalMessageInfo

func (m *IssueBookResp) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *IssueBookResp) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *IssueBookResp) GetIssuerName() string {
	if m != nil {
		return m.IssuerName
	}
	return ""
}

func (m *IssueBookResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*IssueBookReq)(nil), "v1.IssueBookReq")
	proto.RegisterType((*IssueBookResp)(nil), "v1.IssueBookResp")
}

func init() { proto.RegisterFile("library.proto", fileDescriptor_f8a1c5bd42931444) }

var fileDescriptor_f8a1c5bd42931444 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xc9, 0x4c, 0x2a,
	0x4a, 0x2c, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x94, 0xe2, 0x4a,
	0xca, 0xcf, 0xcf, 0x86, 0xf0, 0xa5, 0x74, 0xc0, 0x54, 0xb2, 0x6e, 0x7a, 0x6a, 0x9e, 0x6e, 0x71,
	0x79, 0x62, 0x7a, 0x7a, 0x6a, 0x91, 0x7e, 0x7e, 0x41, 0x49, 0x66, 0x7e, 0x5e, 0xb1, 0x7e, 0x62,
	0x5e, 0x5e, 0x7e, 0x49, 0x22, 0x98, 0x0d, 0x55, 0x2d, 0x93, 0x9e, 0x9f, 0x9f, 0x9e, 0x93, 0xaa,
	0x9f, 0x58, 0x90, 0x89, 0x29, 0xab, 0x14, 0xc7, 0xc5, 0xe3, 0x59, 0x5c, 0x5c, 0x9a, 0xea, 0x94,
	0x9f, 0x9f, 0x1d, 0x94, 0x5a, 0x28, 0x24, 0xc0, 0xc5, 0xec, 0x58, 0x90, 0x29, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0x62, 0x0a, 0xc9, 0x70, 0xb1, 0x80, 0xec, 0x96, 0x60, 0x52, 0x60, 0xd4,
	0xe0, 0x36, 0xe2, 0xd0, 0x2b, 0x33, 0xd4, 0x03, 0x2b, 0x06, 0x8b, 0x0a, 0xc9, 0x71, 0x71, 0x81,
	0xf5, 0x17, 0xf9, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x83, 0xb5, 0x21, 0x89, 0x28, 0x95, 0x73, 0xf1,
	0x22, 0x99, 0x5f, 0x5c, 0x80, 0xdd, 0x02, 0x27, 0xac, 0x16, 0x38, 0x11, 0x61, 0x81, 0x90, 0x18,
	0x17, 0x5b, 0x70, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x04, 0x0b, 0x58, 0x0e, 0xca, 0x33, 0xca, 0xe4,
	0xe2, 0xf3, 0x81, 0x84, 0x62, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x50, 0x38, 0x17, 0x27,
	0xdc, 0x29, 0x42, 0x02, 0x20, 0x6b, 0x90, 0x7d, 0x2e, 0x25, 0x88, 0x26, 0x52, 0x5c, 0xa0, 0xa4,
	0xda, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x79, 0x25, 0x29, 0xfd, 0x32, 0x43, 0x7d, 0x68, 0x9c, 0x14,
	0x43, 0x4c, 0x83, 0x71, 0xad, 0x18, 0xb5, 0x92, 0xd8, 0xc0, 0x41, 0x69, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xd5, 0x84, 0xe2, 0x68, 0xb7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LibraryServiceClient is the client API for LibraryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LibraryServiceClient interface {
	IssueBook(ctx context.Context, in *IssueBookReq, opts ...grpc.CallOption) (*IssueBookResp, error)
}

type libraryServiceClient struct {
	cc *grpc.ClientConn
}

func NewLibraryServiceClient(cc *grpc.ClientConn) LibraryServiceClient {
	return &libraryServiceClient{cc}
}

func (c *libraryServiceClient) IssueBook(ctx context.Context, in *IssueBookReq, opts ...grpc.CallOption) (*IssueBookResp, error) {
	out := new(IssueBookResp)
	err := c.cc.Invoke(ctx, "/v1.LibraryService/IssueBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibraryServiceServer is the server API for LibraryService service.
type LibraryServiceServer interface {
	IssueBook(context.Context, *IssueBookReq) (*IssueBookResp, error)
}

func RegisterLibraryServiceServer(s *grpc.Server, srv LibraryServiceServer) {
	s.RegisterService(&_LibraryService_serviceDesc, srv)
}

func _LibraryService_IssueBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).IssueBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.LibraryService/IssueBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).IssueBook(ctx, req.(*IssueBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LibraryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.LibraryService",
	HandlerType: (*LibraryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueBook",
			Handler:    _LibraryService_IssueBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "library.proto",
}
