// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-management.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Api                  string   `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Qualification        string   `protobuf:"bytes,5,opt,name=Qualification,proto3" json:"Qualification,omitempty"`
	Experience           float32  `protobuf:"fixed32,6,opt,name=Experience,proto3" json:"Experience,omitempty"`
	Password             string   `protobuf:"bytes,7,opt,name=Password,proto3" json:"Password,omitempty"`
	InvitationFlag       int64    `protobuf:"varint,8,opt,name=InvitationFlag,proto3" json:"InvitationFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c93e5259739e1a22, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetQualification() string {
	if m != nil {
		return m.Qualification
	}
	return ""
}

func (m *User) GetExperience() float32 {
	if m != nil {
		return m.Experience
	}
	return 0
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetInvitationFlag() int64 {
	if m != nil {
		return m.InvitationFlag
	}
	return 0
}

type CreateUserResp struct {
	Api                  string   `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	RespCode             string   `protobuf:"bytes,3,opt,name=RespCode,proto3" json:"RespCode,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResp) Reset()         { *m = CreateUserResp{} }
func (m *CreateUserResp) String() string { return proto.CompactTextString(m) }
func (*CreateUserResp) ProtoMessage()    {}
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c93e5259739e1a22, []int{1}
}

func (m *CreateUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResp.Unmarshal(m, b)
}
func (m *CreateUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResp.Marshal(b, m, deterministic)
}
func (m *CreateUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResp.Merge(m, src)
}
func (m *CreateUserResp) XXX_Size() int {
	return xxx_messageInfo_CreateUserResp.Size(m)
}
func (m *CreateUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResp proto.InternalMessageInfo

func (m *CreateUserResp) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateUserResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateUserResp) GetRespCode() string {
	if m != nil {
		return m.RespCode
	}
	return ""
}

func (m *CreateUserResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetUserReq struct {
	Api                  string   `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c93e5259739e1a22, []int{2}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetUserReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*CreateUserResp)(nil), "v1.CreateUserResp")
	proto.RegisterType((*GetUserReq)(nil), "v1.GetUserReq")
}

func init() { proto.RegisterFile("user-management.proto", fileDescriptor_c93e5259739e1a22) }

var fileDescriptor_c93e5259739e1a22 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x8b, 0x13, 0x41,
	0x14, 0xa4, 0x67, 0xb2, 0x49, 0x7c, 0x90, 0x10, 0x9e, 0x1f, 0x0c, 0x41, 0xa4, 0x19, 0x44, 0x42,
	0x30, 0x99, 0x4d, 0x36, 0x5e, 0xd6, 0x83, 0xac, 0xcb, 0x2a, 0x7b, 0x58, 0xd1, 0x01, 0xbd, 0xb7,
	0x93, 0xe7, 0x6c, 0x4b, 0xd2, 0x3d, 0x76, 0x4f, 0x92, 0x3d, 0x7b, 0xf1, 0xae, 0x27, 0x05, 0x7f,
	0x95, 0x7f, 0xc1, 0x83, 0x3f, 0x43, 0xba, 0xf3, 0xbd, 0xbb, 0xa7, 0x79, 0x55, 0x5d, 0x6f, 0xaa,
	0xab, 0x29, 0xb8, 0x3f, 0xb3, 0x64, 0x7a, 0x53, 0xa1, 0x44, 0x4e, 0x53, 0x52, 0x65, 0xbf, 0x30,
	0xba, 0xd4, 0x18, 0xcc, 0x07, 0xed, 0x87, 0xb9, 0xd6, 0xf9, 0x84, 0x12, 0x51, 0xc8, 0x44, 0x28,
	0xa5, 0x4b, 0x51, 0x4a, 0xad, 0xec, 0x52, 0xd1, 0x7e, 0xea, 0x3f, 0x59, 0x2f, 0x27, 0xd5, 0xb3,
	0x0b, 0x91, 0xe7, 0x64, 0x12, 0x5d, 0x78, 0xc5, 0x4d, 0x75, 0xfc, 0x8f, 0x41, 0xe5, 0xbd, 0x25,
	0x83, 0x2d, 0x08, 0x4f, 0x0a, 0x19, 0x31, 0xce, 0x3a, 0x77, 0x52, 0x37, 0x22, 0x42, 0xe5, 0x8d,
	0x98, 0x52, 0x14, 0x78, 0xca, 0xcf, 0x78, 0x0f, 0x0e, 0xce, 0xa6, 0x42, 0x4e, 0xa2, 0xd0, 0x93,
	0x4b, 0x80, 0x6d, 0xa8, 0xbb, 0x7f, 0x78, 0x75, 0xc5, 0x1f, 0x6c, 0x30, 0x3e, 0x86, 0xc6, 0xbb,
	0x99, 0x98, 0xc8, 0x4f, 0x32, 0xf3, 0xc6, 0xd1, 0x81, 0x17, 0xec, 0x93, 0xf8, 0x08, 0xe0, 0xec,
	0xaa, 0x20, 0x23, 0x49, 0x65, 0x14, 0x55, 0x39, 0xeb, 0x04, 0xe9, 0x0e, 0xe3, 0x1c, 0xde, 0x0a,
	0x6b, 0x17, 0xda, 0x8c, 0xa3, 0xda, 0xd2, 0x61, 0x8d, 0xf1, 0x09, 0x34, 0xcf, 0xd5, 0x5c, 0x2e,
	0x73, 0xbd, 0x9a, 0x88, 0x3c, 0xaa, 0x73, 0xd6, 0x09, 0xd3, 0x6b, 0x6c, 0x5c, 0x40, 0xf3, 0xd4,
	0x90, 0x28, 0xc9, 0xdd, 0x2d, 0x25, 0x5b, 0xdc, 0x92, 0xf9, 0x01, 0x54, 0xdd, 0xe9, 0xf9, 0xd8,
	0xa7, 0x0e, 0xd3, 0x15, 0x72, 0xfe, 0x6e, 0xe3, 0x54, 0x8f, 0x69, 0x15, 0x7d, 0x83, 0x31, 0x82,
	0xda, 0x05, 0x59, 0x2b, 0xf2, 0x75, 0xf8, 0x35, 0x8c, 0x3f, 0x00, 0xbc, 0xa6, 0x72, 0x69, 0xf7,
	0xe5, 0x16, 0xb7, 0xdd, 0x77, 0x0b, 0xae, 0xbd, 0xdb, 0x6e, 0xe2, 0x70, 0x3f, 0xf1, 0xf0, 0x1b,
	0x83, 0x86, 0x13, 0x5e, 0xb8, 0x76, 0xb8, 0x72, 0xe0, 0x0b, 0x80, 0x6d, 0x36, 0xac, 0xf7, 0xe7,
	0x83, 0xbe, 0x9b, 0xda, 0xe8, 0xa6, 0xfd, 0xd4, 0xf1, 0xdd, 0xaf, 0x7f, 0xfe, 0xfe, 0x08, 0x1a,
	0x71, 0x3d, 0x99, 0x0f, 0x12, 0xd7, 0xb2, 0x63, 0xd6, 0xc5, 0x67, 0x50, 0x5b, 0x5d, 0x15, 0x9b,
	0x6e, 0x67, 0x7b, 0xef, 0xf6, 0xe6, 0x6f, 0x71, 0xcb, 0x6f, 0x02, 0x6e, 0x36, 0x5f, 0xfe, 0x66,
	0xdf, 0x4f, 0x7e, 0x32, 0x3c, 0x82, 0xc8, 0x41, 0xbe, 0xad, 0xab, 0xe5, 0x96, 0xcc, 0x5c, 0x66,
	0x14, 0x23, 0xb4, 0x72, 0x53, 0x64, 0x3d, 0x61, 0xad, 0xcc, 0x95, 0x3f, 0x1b, 0x86, 0x83, 0xfe,
	0x61, 0x97, 0xb1, 0x61, 0x4b, 0x14, 0xc5, 0x64, 0xd5, 0x81, 0xe4, 0xb3, 0xd5, 0xea, 0xf8, 0x06,
	0x93, 0x3e, 0x87, 0x70, 0x74, 0x38, 0xc2, 0x11, 0x74, 0x53, 0x2a, 0x67, 0x46, 0xd1, 0x98, 0x2f,
	0x2e, 0x49, 0xf1, 0xf2, 0x92, 0xb8, 0x21, 0xab, 0x67, 0x26, 0x23, 0x3e, 0xd6, 0x64, 0xb9, 0xd2,
	0x25, 0xa7, 0x2b, 0x69, 0xcb, 0x3e, 0x56, 0xa1, 0xf2, 0x2b, 0x60, 0xb5, 0x8f, 0x55, 0xdf, 0xf2,
	0xa3, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x81, 0x4f, 0xa4, 0x05, 0x4e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserManagmentClient is the client API for UserManagment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserManagmentClient interface {
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CreateUserResp, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*User, error)
}

type userManagmentClient struct {
	cc *grpc.ClientConn
}

func NewUserManagmentClient(cc *grpc.ClientConn) UserManagmentClient {
	return &userManagmentClient{cc}
}

func (c *userManagmentClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CreateUserResp, error) {
	out := new(CreateUserResp)
	err := c.cc.Invoke(ctx, "/v1.UserManagment/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagmentClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/v1.UserManagment/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagmentServer is the server API for UserManagment service.
type UserManagmentServer interface {
	CreateUser(context.Context, *User) (*CreateUserResp, error)
	GetUser(context.Context, *GetUserReq) (*User, error)
}

func RegisterUserManagmentServer(s *grpc.Server, srv UserManagmentServer) {
	s.RegisterService(&_UserManagment_serviceDesc, srv)
}

func _UserManagment_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagmentServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserManagment/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagmentServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagment_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagmentServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserManagment/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagmentServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserManagment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserManagment",
	HandlerType: (*UserManagmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserManagment_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserManagment_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-management.proto",
}
