// Code generated by protoc-gen-go. DO NOT EDIT.
// source: students.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type API struct {
	Api                  string   `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *API) Reset()         { *m = API{} }
func (m *API) String() string { return proto.CompactTextString(m) }
func (*API) ProtoMessage()    {}
func (*API) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fe5f1867722001e, []int{0}
}

func (m *API) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_API.Unmarshal(m, b)
}
func (m *API) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_API.Marshal(b, m, deterministic)
}
func (m *API) XXX_Merge(src proto.Message) {
	xxx_messageInfo_API.Merge(m, src)
}
func (m *API) XXX_Size() int {
	return xxx_messageInfo_API.Size(m)
}
func (m *API) XXX_DiscardUnknown() {
	xxx_messageInfo_API.DiscardUnknown(m)
}

var xxx_messageInfo_API proto.InternalMessageInfo

func (m *API) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type Student struct {
	RollNo               int64    `protobuf:"varint,1,opt,name=RollNo,proto3" json:"RollNo,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Department           string   `protobuf:"bytes,3,opt,name=Department,proto3" json:"Department,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fe5f1867722001e, []int{1}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetRollNo() int64 {
	if m != nil {
		return m.RollNo
	}
	return 0
}

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetDepartment() string {
	if m != nil {
		return m.Department
	}
	return ""
}

type CreateStudentReq struct {
	Api                  *API     `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	Student              *Student `protobuf:"bytes,2,opt,name=Student,proto3" json:"Student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStudentReq) Reset()         { *m = CreateStudentReq{} }
func (m *CreateStudentReq) String() string { return proto.CompactTextString(m) }
func (*CreateStudentReq) ProtoMessage()    {}
func (*CreateStudentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fe5f1867722001e, []int{2}
}

func (m *CreateStudentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStudentReq.Unmarshal(m, b)
}
func (m *CreateStudentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStudentReq.Marshal(b, m, deterministic)
}
func (m *CreateStudentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStudentReq.Merge(m, src)
}
func (m *CreateStudentReq) XXX_Size() int {
	return xxx_messageInfo_CreateStudentReq.Size(m)
}
func (m *CreateStudentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStudentReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStudentReq proto.InternalMessageInfo

func (m *CreateStudentReq) GetApi() *API {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *CreateStudentReq) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type CreateStudentResp struct {
	Api                  *API     `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	Student              *Student `protobuf:"bytes,2,opt,name=Student,proto3" json:"Student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStudentResp) Reset()         { *m = CreateStudentResp{} }
func (m *CreateStudentResp) String() string { return proto.CompactTextString(m) }
func (*CreateStudentResp) ProtoMessage()    {}
func (*CreateStudentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fe5f1867722001e, []int{3}
}

func (m *CreateStudentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStudentResp.Unmarshal(m, b)
}
func (m *CreateStudentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStudentResp.Marshal(b, m, deterministic)
}
func (m *CreateStudentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStudentResp.Merge(m, src)
}
func (m *CreateStudentResp) XXX_Size() int {
	return xxx_messageInfo_CreateStudentResp.Size(m)
}
func (m *CreateStudentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStudentResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStudentResp proto.InternalMessageInfo

func (m *CreateStudentResp) GetApi() *API {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *CreateStudentResp) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type ReadAllStudentRecordsResp struct {
	Api                  *API       `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	Student              []*Student `protobuf:"bytes,2,rep,name=Student,proto3" json:"Student,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadAllStudentRecordsResp) Reset()         { *m = ReadAllStudentRecordsResp{} }
func (m *ReadAllStudentRecordsResp) String() string { return proto.CompactTextString(m) }
func (*ReadAllStudentRecordsResp) ProtoMessage()    {}
func (*ReadAllStudentRecordsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fe5f1867722001e, []int{4}
}

func (m *ReadAllStudentRecordsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllStudentRecordsResp.Unmarshal(m, b)
}
func (m *ReadAllStudentRecordsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllStudentRecordsResp.Marshal(b, m, deterministic)
}
func (m *ReadAllStudentRecordsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllStudentRecordsResp.Merge(m, src)
}
func (m *ReadAllStudentRecordsResp) XXX_Size() int {
	return xxx_messageInfo_ReadAllStudentRecordsResp.Size(m)
}
func (m *ReadAllStudentRecordsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllStudentRecordsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllStudentRecordsResp proto.InternalMessageInfo

func (m *ReadAllStudentRecordsResp) GetApi() *API {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *ReadAllStudentRecordsResp) GetStudent() []*Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type ReadAllStudentRecordsReq struct {
	Api                  *API     `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllStudentRecordsReq) Reset()         { *m = ReadAllStudentRecordsReq{} }
func (m *ReadAllStudentRecordsReq) String() string { return proto.CompactTextString(m) }
func (*ReadAllStudentRecordsReq) ProtoMessage()    {}
func (*ReadAllStudentRecordsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fe5f1867722001e, []int{5}
}

func (m *ReadAllStudentRecordsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllStudentRecordsReq.Unmarshal(m, b)
}
func (m *ReadAllStudentRecordsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllStudentRecordsReq.Marshal(b, m, deterministic)
}
func (m *ReadAllStudentRecordsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllStudentRecordsReq.Merge(m, src)
}
func (m *ReadAllStudentRecordsReq) XXX_Size() int {
	return xxx_messageInfo_ReadAllStudentRecordsReq.Size(m)
}
func (m *ReadAllStudentRecordsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllStudentRecordsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllStudentRecordsReq proto.InternalMessageInfo

func (m *ReadAllStudentRecordsReq) GetApi() *API {
	if m != nil {
		return m.Api
	}
	return nil
}

func init() {
	proto.RegisterType((*API)(nil), "v1.API")
	proto.RegisterType((*Student)(nil), "v1.Student")
	proto.RegisterType((*CreateStudentReq)(nil), "v1.CreateStudentReq")
	proto.RegisterType((*CreateStudentResp)(nil), "v1.CreateStudentResp")
	proto.RegisterType((*ReadAllStudentRecordsResp)(nil), "v1.ReadAllStudentRecordsResp")
	proto.RegisterType((*ReadAllStudentRecordsReq)(nil), "v1.ReadAllStudentRecordsReq")
}

func init() { proto.RegisterFile("students.proto", fileDescriptor_3fe5f1867722001e) }

var fileDescriptor_3fe5f1867722001e = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0x12,
	0xe7, 0x62, 0x76, 0x0c, 0xf0, 0x14, 0x12, 0xe0, 0x62, 0x76, 0x2c, 0xc8, 0x94, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x42, 0xb9, 0xd8, 0x83, 0x21, 0xca, 0x85, 0xc4, 0xb8, 0xd8,
	0x82, 0xf2, 0x73, 0x72, 0xfc, 0xf2, 0xc1, 0xf2, 0xcc, 0x41, 0x50, 0x9e, 0x90, 0x10, 0x17, 0x8b,
	0x5f, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x17, 0x98, 0x2d, 0x24, 0xc7, 0xc5, 0xe5, 0x92, 0x5a,
	0x90, 0x58, 0x54, 0x92, 0x9b, 0x9a, 0x57, 0x22, 0xc1, 0x0c, 0x96, 0x41, 0x12, 0x51, 0x0a, 0xe1,
	0x12, 0x70, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x85, 0x1a, 0x1e, 0x94, 0x5a, 0x28, 0x24, 0x89, 0xb0,
	0x9c, 0xdb, 0x88, 0x5d, 0xaf, 0xcc, 0x50, 0xcf, 0x31, 0xc0, 0x13, 0xec, 0x0a, 0x21, 0x55, 0xb8,
	0x2b, 0xc0, 0xb6, 0x70, 0x1b, 0x71, 0x83, 0xa4, 0x61, 0x7a, 0x61, 0x72, 0x4a, 0xa1, 0x5c, 0x82,
	0x68, 0xa6, 0x16, 0x17, 0x50, 0xc1, 0xd8, 0x58, 0x2e, 0xc9, 0xa0, 0xd4, 0xc4, 0x14, 0xc7, 0x9c,
	0x1c, 0xb8, 0xb9, 0xc9, 0xf9, 0x45, 0x29, 0xc5, 0x24, 0x19, 0xcf, 0x8c, 0xd3, 0x78, 0x53, 0x2e,
	0x09, 0x1c, 0xc6, 0xe3, 0x0b, 0x13, 0xa3, 0xd5, 0x8c, 0x5c, 0x7c, 0x50, 0x0d, 0xc1, 0xa9, 0x45,
	0x65, 0x99, 0xc9, 0xa9, 0x42, 0xf6, 0xb0, 0x50, 0xf5, 0x4b, 0x2d, 0x87, 0xc5, 0x9a, 0x08, 0x48,
	0x13, 0x7a, 0x58, 0x4b, 0x89, 0x62, 0x11, 0x2d, 0x2e, 0x10, 0x8a, 0xe0, 0x12, 0xc5, 0xea, 0x14,
	0x21, 0x19, 0x90, 0x7a, 0x5c, 0xae, 0x94, 0x92, 0xc5, 0x23, 0x5b, 0x5c, 0xa0, 0xc1, 0x68, 0xc0,
	0x98, 0xc4, 0x06, 0x4e, 0x6b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xc9, 0xa8, 0xd4,
	0x7d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StudentServiceClient is the client API for StudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentServiceClient interface {
	CreateNewStudent(ctx context.Context, in *CreateStudentReq, opts ...grpc.CallOption) (*CreateStudentResp, error)
	ReadAllStudentRecords(ctx context.Context, opts ...grpc.CallOption) (StudentService_ReadAllStudentRecordsClient, error)
}

type studentServiceClient struct {
	cc *grpc.ClientConn
}

func NewStudentServiceClient(cc *grpc.ClientConn) StudentServiceClient {
	return &studentServiceClient{cc}
}

func (c *studentServiceClient) CreateNewStudent(ctx context.Context, in *CreateStudentReq, opts ...grpc.CallOption) (*CreateStudentResp, error) {
	out := new(CreateStudentResp)
	err := c.cc.Invoke(ctx, "/v1.StudentService/CreateNewStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) ReadAllStudentRecords(ctx context.Context, opts ...grpc.CallOption) (StudentService_ReadAllStudentRecordsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StudentService_serviceDesc.Streams[0], "/v1.StudentService/ReadAllStudentRecords", opts...)
	if err != nil {
		return nil, err
	}
	x := &studentServiceReadAllStudentRecordsClient{stream}
	return x, nil
}

type StudentService_ReadAllStudentRecordsClient interface {
	Send(*ReadAllStudentRecordsReq) error
	Recv() (*ReadAllStudentRecordsResp, error)
	grpc.ClientStream
}

type studentServiceReadAllStudentRecordsClient struct {
	grpc.ClientStream
}

func (x *studentServiceReadAllStudentRecordsClient) Send(m *ReadAllStudentRecordsReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *studentServiceReadAllStudentRecordsClient) Recv() (*ReadAllStudentRecordsResp, error) {
	m := new(ReadAllStudentRecordsResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StudentServiceServer is the server API for StudentService service.
type StudentServiceServer interface {
	CreateNewStudent(context.Context, *CreateStudentReq) (*CreateStudentResp, error)
	ReadAllStudentRecords(StudentService_ReadAllStudentRecordsServer) error
}

func RegisterStudentServiceServer(s *grpc.Server, srv StudentServiceServer) {
	s.RegisterService(&_StudentService_serviceDesc, srv)
}

func _StudentService_CreateNewStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).CreateNewStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.StudentService/CreateNewStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).CreateNewStudent(ctx, req.(*CreateStudentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_ReadAllStudentRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StudentServiceServer).ReadAllStudentRecords(&studentServiceReadAllStudentRecordsServer{stream})
}

type StudentService_ReadAllStudentRecordsServer interface {
	Send(*ReadAllStudentRecordsResp) error
	Recv() (*ReadAllStudentRecordsReq, error)
	grpc.ServerStream
}

type studentServiceReadAllStudentRecordsServer struct {
	grpc.ServerStream
}

func (x *studentServiceReadAllStudentRecordsServer) Send(m *ReadAllStudentRecordsResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *studentServiceReadAllStudentRecordsServer) Recv() (*ReadAllStudentRecordsReq, error) {
	m := new(ReadAllStudentRecordsReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _StudentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.StudentService",
	HandlerType: (*StudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewStudent",
			Handler:    _StudentService_CreateNewStudent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadAllStudentRecords",
			Handler:       _StudentService_ReadAllStudentRecords_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "students.proto",
}
